# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'vk-api' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for vk-api

pod 'Alamofire'
pod 'SwiftKeychainWrapper'
pod 'RealmSwift'
pod 'Kingfisher'
pod 'DynamicJSON'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Firestore'
pod 'PromiseKit'
pod 'SwiftyJSON'
end
